# Site settings
title: animal law China
email: animallawchina@gmail.com
description:  123
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
